name: Run Smoke Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12.2
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run docker-compose
        run: docker-compose up -d
      
      - name: Setup Workspace
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade robotframework-seleniumlibrary
      
      - name: Run Smoke Tests
        run: |
          robot --variable BROWSER:chrome --include smoke -d results e2e_tests/tests/
      
