name: Run Smoke Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run docker-compose
        run: docker-compose up -d
      
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12.2
      
      - name: Setup Workspace
        run: |
          python -m venv .venv
          source venv/bin/activate
          pip install --upgrade robotframework-seleniumlibrary
      
      - name: Run Smoke Tests
        run: |
          robot --variable BROWSER:chrome --include smoke -d results e2e_tests/tests/
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: rf-results
          path: results/