name: Run Smoke Tests

on:
  push:
    branches:
      - main

jobs:
  run-smoke-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install robotframework robotframework-seleniumlibrary selenium

      # Step 4: Install Chromium Browser and Driver
      - name: Install Browser and Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-driver

      # Step 5: Run Smoke Tests
      - name: Run Smoke Tests
        run: |
          source venv/bin/activate
          robot --variable BROWSER:chrome --include smoke -d results e2e_tests/tests/

      # Step 6: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-results
          path: results/
