name: Run Smoke Tests

on:
  push:
    branches:
      - main

jobs:
  run-smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4


      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install robotframework robotframework-seleniumlibrary selenium

      - name: Download Browser Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-driver

      - name: Run Smoke Tests
        run: |
          source venv/bin/activate
          robot --include smoke -d results e2e_tests/tests/

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-results
          path: results/
